import { Book } from "./Book.js";

export const BooksList = (props) => {
  return (
    <div>
      <ul>
        <li>
          <Book
            title={props.books[0].title}
            subtitle={props.books[0].subtitle}
            author={props.books[0].author}
            price={props.books[0].price}
          />
        </li>
        <li>
          <Book
            title={props.books[1].title}
            subtitle={props.books[1].subtitle}
            author={props.books[1].author}
            price={props.books[1].price}
          />
        </li>
        <li>
          <Book
            title={props.books[2].title}
            subtitle={props.books[2].subtitle}
            author={props.books[2].author}
            price={props.books[2].price}
          />
        </li>
        <li>
          <Book
            title={props.books[3].title}
            subtitle={props.books[3].subtitle}
            author={props.books[3].author}
            price={props.books[3].price}
          />
        </li>
        <li>
          <Book
            title={props.books[4].title}
            subtitle={props.books[4].subtitle}
            author={props.books[4].author}
            price={props.books[4].price}
          />
        </li>
        <li>
          <Book
            title={props.books[5].title}
            subtitle={props.books[5].subtitle}
            author={props.books[5].author}
            price={props.books[5].price}
          />
        </li>
        <li>
          <Book
            title={props.books[6].title}
            subtitle={props.books[6].subtitle}
            author={props.books[6].author}
            price={props.books[6].price}
          />
        </li>
        <li>
          <Book
            title={props.books[7].title}
            subtitle={props.books[7].subtitle}
            author={props.books[7].author}
            price={props.books[7].price}
          />
        </li>
      </ul>
    </div>
  );
};
